import Banner from "@/components/Banner";
import CardListing from "@/components/CardListing";
import GroupTravel from "@/components/GroupTravel";
import Moments from "@/components/Moments";
import Testimonials from "@/components/Testimonials";
import Title from "@/components/Title";
import { Arrangements, Momentss, TestimonalCard } from "@/interface/type";
import { GetStaticProps } from "next";
import Head from "next/head";

interface Props {
  arangments: Arrangements[];
  testimonials: TestimonalCard[];
  moments: Momentss[];
}

const Home: React.FC<Props> = ({ arangments, moments, testimonials }) => {
  return (
    <>
      <Head>
        <title>Т.А Инфинити Травел</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Banner bannerImg="banner" />
      <Title title="Актуелни понуди" />
      <CardListing cardData={arangments} arrow="SeeMore" linkTo="destinacii" />
      <GroupTravel />
      <Testimonials dataTestimonialsCard={testimonials} />
      <Moments cardData={moments} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const resArangments = await fetch(
    "https://infinity-travel.glitch.me/arrangements?isTrending_like=true"
  );
  const arangments: Arrangements[] = await resArangments.json();

  const resTestimonials = await fetch(
    "https://infinity-travel.glitch.me/testimonials"
  );
  const testimonials: TestimonalCard[] = await resTestimonials.json();

  const resMoments = await fetch("https://infinity-travel.glitch.me/moments");
  const moments: Momentss[] = await resMoments.json();

  return {
    props: {
      arangments,
      testimonials,
      moments,
    },
  };
};

export default Home;
